name: "CI CD Pipeline Thomas Kaestner"

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cache node modules
      - uses: actions/cache@v1
        with:
          node-version: '14'
      - name: Install
      - run: npm install

      - name: Test
      - run: npm test

      - name: Build
      - run: npm run build

      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: .
          destination_dir: .