name: Vue Build and Deploy

on:
    push:
        branches:
            - master # Change this to the branch you want to trigger the workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14

            - name: Install Dependencies
              run: npm install

            - name: Build Vue.js Project
              run: npm run build

            - name: Debug Output
              run: |
                ls -la ./dist

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/shit
                  base_dir: ./dist/shit # Add this line to set the base directory